CREATE TABLE "indecaters" (
	"id" SERIAL NOT NULL,
	"inn" VARCHAR(20) NOT NULL,
	"ogrn" VARCHAR(20) NOT NULL,
	"name" VARCHAR(500) NOT NULL,
	"full_name" TEXT NULL DEFAULT NULL,
	"spark_status" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"internal_status" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"final_status" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"registration_date" DATE NULL DEFAULT NULL,
	"added_to_registry_date" DATE NULL DEFAULT NULL,
	"legal_address" TEXT NULL DEFAULT NULL,
	"production_address" TEXT NULL DEFAULT NULL,
	"additional_site_address" TEXT NULL DEFAULT NULL,
	"main_industry" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"main_subindustry" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"additional_industry" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"additional_subindustry" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"industry_presentations" TEXT NULL DEFAULT NULL,
	"main_okved_code" VARCHAR(20) NULL DEFAULT NULL::character varying,
	"main_okved_activity" TEXT NULL DEFAULT NULL,
	"production_okved_code" VARCHAR(20) NULL DEFAULT NULL::character varying,
	"production_okved_activity" TEXT NULL DEFAULT NULL,
	"company_info" TEXT NULL DEFAULT NULL,
	"company_size_category" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"company_size_by_staff" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"company_size_by_revenue" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"leader_name" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"head_organization" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"head_organization_inn" VARCHAR(20) NULL DEFAULT NULL::character varying,
	"head_organization_relation_type" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"leader_contacts" TEXT NULL DEFAULT NULL,
	"leader_email" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"employee_contact" TEXT NULL DEFAULT NULL,
	"phone_number" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"emergency_contact" TEXT NULL DEFAULT NULL,
	"website" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"general_email" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"support_measures_info" TEXT NULL DEFAULT NULL,
	"has_special_status" BOOLEAN NULL DEFAULT NULL,
	"summary_site" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"got_moscow_support" BOOLEAN NULL DEFAULT NULL,
	"is_systemically_important" BOOLEAN NULL DEFAULT NULL,
	"msp_status" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"is_the_one" BOOLEAN NULL DEFAULT NULL,
	"has_state_order" BOOLEAN NULL DEFAULT NULL,
	"production_capacity_utilization" NUMERIC(5,2) NULL DEFAULT NULL::numeric,
	"has_export_supplies" BOOLEAN NULL DEFAULT NULL,
	"export_volume_previous_year" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"export_countries_list" TEXT NULL DEFAULT NULL,
	"tn_ved_code" VARCHAR(50) NULL DEFAULT NULL::character varying,
	"industry_by_spark_and_ref" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"district" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"area" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"revenue" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"net_profit" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"total_staff" INTEGER NULL DEFAULT NULL,
	"moscow_staff" INTEGER NULL DEFAULT NULL,
	"total_payroll" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"moscow_payroll" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"avg_salary_total" NUMERIC(10,2) NULL DEFAULT NULL::numeric,
	"avg_salary_moscow" NUMERIC(10,2) NULL DEFAULT NULL::numeric,
	"total_taxes" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"profit_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"property_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"land_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"personal_income_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"transport_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"other_taxes" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"excise_tax" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"investments_moscow" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"export_volume" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"land_cadastral_number" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"land_area" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"land_permitted_use" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"land_ownership_type" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"land_owner" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"building_cadastral_number" VARCHAR(100) NULL DEFAULT NULL::character varying,
	"building_area" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"building_permitted_use" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"building_type_and_purpose" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"building_ownership_type" VARCHAR(255) NULL DEFAULT NULL::character varying,
	"building_owner" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"production_area" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"product_name" TEXT NULL DEFAULT NULL,
	"standardized_product_name" VARCHAR(500) NULL DEFAULT NULL::character varying,
	"produced_products_list" TEXT NULL DEFAULT NULL,
	"products_by_type_and_segment" TEXT NULL DEFAULT NULL,
	"product_catalog" TEXT NULL DEFAULT NULL,
	"legal_address_latitude" NUMERIC(10,8) NULL DEFAULT NULL::numeric,
	"legal_address_longitude" NUMERIC(11,8) NULL DEFAULT NULL::numeric,
	"production_address_latitude" NUMERIC(10,8) NULL DEFAULT NULL::numeric,
	"production_address_longitude" NUMERIC(11,8) NULL DEFAULT NULL::numeric,
	"additional_site_latitude" NUMERIC(10,8) NULL DEFAULT NULL::numeric,
	"additional_site_longitude" NUMERIC(11,8) NULL DEFAULT NULL::numeric,
	"start_period" TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
	"finish_period" TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
	"revision" BIGINT NULL DEFAULT 0,
	"destroyed" BOOLEAN NULL DEFAULT false,
	"created_at" TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
	"total_assets" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"equity" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"fixed_assets" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"current_assets" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"long_term_liabilities" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"short_term_liabilities" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"cash" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"accounts_receivable" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	"inventory" NUMERIC(15,2) NULL DEFAULT NULL::numeric,
	PRIMARY KEY ("id")
)
;

