// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Базовые сообщения для CRUD операций
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BinaryFields  map[string][]byte      `protobuf:"bytes,3,rep,name=binary_fields,json=binaryFields,proto3" json:"binary_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Entity) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Entity) GetBinaryFields() map[string][]byte {
	if x != nil {
		return x.BinaryFields
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Entity        *Entity                `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Entity        *Entity                `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,3,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteRequest) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedRows  int32                  `protobuf:"varint,2,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderDesc     bool                   `protobuf:"varint,5,opt,name=order_desc,json=orderDesc,proto3" json:"order_desc,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListRequest) GetOrderDesc() bool {
	if x != nil {
		return x.OrderDesc
	}
	return false
}

func (x *ListRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type EntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Entity        *Entity                `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *EntityResponse) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *EntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Пакетные операции
type BatchCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRequest) Reset() {
	*x = BatchCreateRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRequest) ProtoMessage() {}

func (x *BatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *BatchCreateRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *BatchCreateRequest) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BatchUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateRequest) Reset() {
	*x = BatchUpdateRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateRequest) ProtoMessage() {}

func (x *BatchUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *BatchUpdateRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *BatchUpdateRequest) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Ids           []int32                `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	AffectedRows  int32                  `protobuf:"varint,3,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *BatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchResponse) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchResponse) GetAffectedRows() int32 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

func (x *BatchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Специализированные сообщения (добавлены обратно)
type GetOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetOrganizationRequest_Id
	//	*GetOrganizationRequest_Inn
	Identifier    isGetOrganizationRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrganizationRequest) GetIdentifier() isGetOrganizationRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetOrganizationRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.Identifier.(*GetOrganizationRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetOrganizationRequest) GetInn() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetOrganizationRequest_Inn); ok {
			return x.Inn
		}
	}
	return ""
}

type isGetOrganizationRequest_Identifier interface {
	isGetOrganizationRequest_Identifier()
}

type GetOrganizationRequest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetOrganizationRequest_Inn struct {
	Inn string `protobuf:"bytes,2,opt,name=inn,proto3,oneof"`
}

func (*GetOrganizationRequest_Id) isGetOrganizationRequest_Identifier() {}

func (*GetOrganizationRequest_Inn) isGetOrganizationRequest_Identifier() {}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrganizationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type SearchOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrganizationsRequest) Reset() {
	*x = SearchOrganizationsRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrganizationsRequest) ProtoMessage() {}

func (x *SearchOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*SearchOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *SearchOrganizationsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchOrganizationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OrganizationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Organization        *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Addresses           []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Contacts            []*Contact             `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	FinancialIndicators []*FinancialIndicator  `protobuf:"bytes,4,rep,name=financial_indicators,json=financialIndicators,proto3" json:"financial_indicators,omitempty"`
	StaffIndicators     []*StaffIndicator      `protobuf:"bytes,5,rep,name=staff_indicators,json=staffIndicators,proto3" json:"staff_indicators,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrganizationResponse) Reset() {
	*x = OrganizationResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationResponse) ProtoMessage() {}

func (x *OrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationResponse.ProtoReflect.Descriptor instead.
func (*OrganizationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *OrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *OrganizationResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *OrganizationResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *OrganizationResponse) GetFinancialIndicators() []*FinancialIndicator {
	if x != nil {
		return x.FinancialIndicators
	}
	return nil
}

func (x *OrganizationResponse) GetStaffIndicators() []*StaffIndicator {
	if x != nil {
		return x.StaffIndicators
	}
	return nil
}

type Organization struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Inn                     string                 `protobuf:"bytes,2,opt,name=inn,proto3" json:"inn,omitempty"`
	Name                    string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FullName                string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	SparkStatus             string                 `protobuf:"bytes,5,opt,name=spark_status,json=sparkStatus,proto3" json:"spark_status,omitempty"`
	InternalStatus          string                 `protobuf:"bytes,6,opt,name=internal_status,json=internalStatus,proto3" json:"internal_status,omitempty"`
	FinalStatus             string                 `protobuf:"bytes,7,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	RegistrationDate        string                 `protobuf:"bytes,8,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	AddedToRegistryDate     string                 `protobuf:"bytes,9,opt,name=added_to_registry_date,json=addedToRegistryDate,proto3" json:"added_to_registry_date,omitempty"`
	HasSpecialStatus        bool                   `protobuf:"varint,10,opt,name=has_special_status,json=hasSpecialStatus,proto3" json:"has_special_status,omitempty"`
	IsSystemicallyImportant bool                   `protobuf:"varint,11,opt,name=is_systemically_important,json=isSystemicallyImportant,proto3" json:"is_systemically_important,omitempty"`
	MspStatus               string                 `protobuf:"bytes,12,opt,name=msp_status,json=mspStatus,proto3" json:"msp_status,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *Organization) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Organization) GetSparkStatus() string {
	if x != nil {
		return x.SparkStatus
	}
	return ""
}

func (x *Organization) GetInternalStatus() string {
	if x != nil {
		return x.InternalStatus
	}
	return ""
}

func (x *Organization) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

func (x *Organization) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

func (x *Organization) GetAddedToRegistryDate() string {
	if x != nil {
		return x.AddedToRegistryDate
	}
	return ""
}

func (x *Organization) GetHasSpecialStatus() bool {
	if x != nil {
		return x.HasSpecialStatus
	}
	return false
}

func (x *Organization) GetIsSystemicallyImportant() bool {
	if x != nil {
		return x.IsSystemicallyImportant
	}
	return false
}

func (x *Organization) GetMspStatus() string {
	if x != nil {
		return x.MspStatus
	}
	return ""
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AddressType   string                 `protobuf:"bytes,2,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *Address) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaderName    string                 `protobuf:"bytes,2,opt,name=leader_name,json=leaderName,proto3" json:"leader_name,omitempty"`
	LeaderEmail   string                 `protobuf:"bytes,3,opt,name=leader_email,json=leaderEmail,proto3" json:"leader_email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	GeneralEmail  string                 `protobuf:"bytes,6,opt,name=general_email,json=generalEmail,proto3" json:"general_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *Contact) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contact) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *Contact) GetLeaderEmail() string {
	if x != nil {
		return x.LeaderEmail
	}
	return ""
}

func (x *Contact) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Contact) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Contact) GetGeneralEmail() string {
	if x != nil {
		return x.GeneralEmail
	}
	return ""
}

type FinancialIndicator struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year              int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Revenue           float64                `protobuf:"fixed64,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	NetProfit         float64                `protobuf:"fixed64,4,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`
	InvestmentsMoscow float64                `protobuf:"fixed64,5,opt,name=investments_moscow,json=investmentsMoscow,proto3" json:"investments_moscow,omitempty"`
	ExportVolume      float64                `protobuf:"fixed64,6,opt,name=export_volume,json=exportVolume,proto3" json:"export_volume,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FinancialIndicator) Reset() {
	*x = FinancialIndicator{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialIndicator) ProtoMessage() {}

func (x *FinancialIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialIndicator.ProtoReflect.Descriptor instead.
func (*FinancialIndicator) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *FinancialIndicator) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FinancialIndicator) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FinancialIndicator) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *FinancialIndicator) GetNetProfit() float64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

func (x *FinancialIndicator) GetInvestmentsMoscow() float64 {
	if x != nil {
		return x.InvestmentsMoscow
	}
	return 0
}

func (x *FinancialIndicator) GetExportVolume() float64 {
	if x != nil {
		return x.ExportVolume
	}
	return 0
}

type StaffIndicator struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Year              int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	TotalStaff        int32                  `protobuf:"varint,3,opt,name=total_staff,json=totalStaff,proto3" json:"total_staff,omitempty"`
	MoscowStaff       int32                  `protobuf:"varint,4,opt,name=moscow_staff,json=moscowStaff,proto3" json:"moscow_staff,omitempty"`
	TotalPayrollFund  float64                `protobuf:"fixed64,5,opt,name=total_payroll_fund,json=totalPayrollFund,proto3" json:"total_payroll_fund,omitempty"`
	MoscowPayrollFund float64                `protobuf:"fixed64,6,opt,name=moscow_payroll_fund,json=moscowPayrollFund,proto3" json:"moscow_payroll_fund,omitempty"`
	AvgSalaryTotal    float64                `protobuf:"fixed64,7,opt,name=avg_salary_total,json=avgSalaryTotal,proto3" json:"avg_salary_total,omitempty"`
	AvgSalaryMoscow   float64                `protobuf:"fixed64,8,opt,name=avg_salary_moscow,json=avgSalaryMoscow,proto3" json:"avg_salary_moscow,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StaffIndicator) Reset() {
	*x = StaffIndicator{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffIndicator) ProtoMessage() {}

func (x *StaffIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffIndicator.ProtoReflect.Descriptor instead.
func (*StaffIndicator) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *StaffIndicator) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaffIndicator) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *StaffIndicator) GetTotalStaff() int32 {
	if x != nil {
		return x.TotalStaff
	}
	return 0
}

func (x *StaffIndicator) GetMoscowStaff() int32 {
	if x != nil {
		return x.MoscowStaff
	}
	return 0
}

func (x *StaffIndicator) GetTotalPayrollFund() float64 {
	if x != nil {
		return x.TotalPayrollFund
	}
	return 0
}

func (x *StaffIndicator) GetMoscowPayrollFund() float64 {
	if x != nil {
		return x.MoscowPayrollFund
	}
	return 0
}

func (x *StaffIndicator) GetAvgSalaryTotal() float64 {
	if x != nil {
		return x.AvgSalaryTotal
	}
	return 0
}

func (x *StaffIndicator) GetAvgSalaryMoscow() float64 {
	if x != nil {
		return x.AvgSalaryMoscow
	}
	return 0
}

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Email
	Identifier    isGetUserRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserRequest) GetIdentifier() isGetUserRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isGetUserRequest_Identifier interface {
	isGetUserRequest_Identifier()
}

type GetUserRequest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Email) isGetUserRequest_Identifier() {}

type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone          string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	OrganizationId int32                  `protobuf:"varint,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RoleId         int32                  `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *CreateUserRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone          string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	OrganizationId int32                  `protobuf:"varint,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RoleId         int32                  `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsVerified     bool                   `protobuf:"varint,9,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	LastLogin      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *User) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateInviteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId int32                  `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RoleId         int32                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreatedBy      int32                  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ExpiresDays    int32                  `protobuf:"varint,5,opt,name=expires_days,json=expiresDays,proto3" json:"expires_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *CreateInviteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInviteRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *CreateInviteRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateInviteRequest) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateInviteRequest) GetExpiresDays() int32 {
	if x != nil {
		return x.ExpiresDays
	}
	return 0
}

type ValidateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInviteRequest) Reset() {
	*x = ValidateInviteRequest{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInviteRequest) ProtoMessage() {}

func (x *ValidateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInviteRequest.ProtoReflect.Descriptor instead.
func (*ValidateInviteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *ValidateInviteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UseInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseInviteRequest) Reset() {
	*x = UseInviteRequest{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseInviteRequest) ProtoMessage() {}

func (x *UseInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseInviteRequest.ProtoReflect.Descriptor instead.
func (*UseInviteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *UseInviteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UseInviteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UseInviteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UseInviteRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UseInviteRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UseInviteRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type InviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        *Invite                `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteResponse) Reset() {
	*x = InviteResponse{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResponse) ProtoMessage() {}

func (x *InviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResponse.ProtoReflect.Descriptor instead.
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *InviteResponse) GetInvite() *Invite {
	if x != nil {
		return x.Invite
	}
	return nil
}

type Invite struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId int32                  `protobuf:"varint,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RoleId         int32                  `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	IsUsed         bool                   `protobuf:"varint,6,opt,name=is_used,json=isUsed,proto3" json:"is_used,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *Invite) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Invite) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invite) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *Invite) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Invite) GetIsUsed() bool {
	if x != nil {
		return x.IsUsed
	}
	return false
}

func (x *Invite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubmitFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        int32                  `protobuf:"varint,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FormData      []byte                 `protobuf:"bytes,3,opt,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFormRequest) Reset() {
	*x = SubmitFormRequest{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFormRequest) ProtoMessage() {}

func (x *SubmitFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFormRequest.ProtoReflect.Descriptor instead.
func (*SubmitFormRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

func (x *SubmitFormRequest) GetFormId() int32 {
	if x != nil {
		return x.FormId
	}
	return 0
}

func (x *SubmitFormRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitFormRequest) GetFormData() []byte {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *SubmitFormRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type GetFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        int32                  `protobuf:"varint,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormRequest) Reset() {
	*x = GetFormRequest{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormRequest) ProtoMessage() {}

func (x *GetFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormRequest.ProtoReflect.Descriptor instead.
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *GetFormRequest) GetFormId() int32 {
	if x != nil {
		return x.FormId
	}
	return 0
}

func (x *GetFormRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FormId        int32                  `protobuf:"varint,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FormData      []byte                 `protobuf:"bytes,5,opt,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormResponse) Reset() {
	*x = FormResponse{}
	mi := &file_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormResponse) ProtoMessage() {}

func (x *FormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormResponse.ProtoReflect.Descriptor instead.
func (*FormResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{34}
}

func (x *FormResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FormResponse) GetFormId() int32 {
	if x != nil {
		return x.FormId
	}
	return 0
}

func (x *FormResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FormResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FormResponse) GetFormData() []byte {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *FormResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetFinancialDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId int32                  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Year           int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFinancialDataRequest) Reset() {
	*x = GetFinancialDataRequest{}
	mi := &file_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinancialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinancialDataRequest) ProtoMessage() {}

func (x *GetFinancialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinancialDataRequest.ProtoReflect.Descriptor instead.
func (*GetFinancialDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{35}
}

func (x *GetFinancialDataRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *GetFinancialDataRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FinancialDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indicators    []*FinancialIndicator  `protobuf:"bytes,1,rep,name=indicators,proto3" json:"indicators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialDataResponse) Reset() {
	*x = FinancialDataResponse{}
	mi := &file_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialDataResponse) ProtoMessage() {}

func (x *FinancialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialDataResponse.ProtoReflect.Descriptor instead.
func (*FinancialDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{36}
}

func (x *FinancialDataResponse) GetIndicators() []*FinancialIndicator {
	if x != nil {
		return x.Indicators
	}
	return nil
}

type GetStaffDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId int32                  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Year           int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStaffDataRequest) Reset() {
	*x = GetStaffDataRequest{}
	mi := &file_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffDataRequest) ProtoMessage() {}

func (x *GetStaffDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffDataRequest.ProtoReflect.Descriptor instead.
func (*GetStaffDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{37}
}

func (x *GetStaffDataRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *GetStaffDataRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type StaffDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indicators    []*StaffIndicator      `protobuf:"bytes,1,rep,name=indicators,proto3" json:"indicators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffDataResponse) Reset() {
	*x = StaffDataResponse{}
	mi := &file_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffDataResponse) ProtoMessage() {}

func (x *StaffDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffDataResponse.ProtoReflect.Descriptor instead.
func (*StaffDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{38}
}

func (x *StaffDataResponse) GetIndicators() []*StaffIndicator {
	if x != nil {
		return x.Indicators
	}
	return nil
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{39}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\x06Entity\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12/\n" +
	"\x06fields\x18\x02 \x03(\v2\x17.api.Entity.FieldsEntryR\x06fields\x12B\n" +
	"\rbinary_fields\x18\x03 \x03(\v2\x1d.api.Entity.BinaryFieldsEntryR\fbinaryFields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11BinaryFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"S\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12#\n" +
	"\x06entity\x18\x02 \x01(\v2\v.api.EntityR\x06entity\"\xaf\x01\n" +
	"\n" +
	"GetRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x126\n" +
	"\afilters\x18\x03 \x03(\v2\x1c.api.GetRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12#\n" +
	"\x06entity\x18\x03 \x01(\v2\v.api.EntityR\x06entity\"_\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1f\n" +
	"\vsoft_delete\x18\x03 \x01(\bR\n" +
	"softDelete\"O\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\raffected_rows\x18\x02 \x01(\x05R\faffectedRows\"\x8c\x02\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12\x1d\n" +
	"\n" +
	"order_desc\x18\x05 \x01(\bR\torderDesc\x127\n" +
	"\afilters\x18\x06 \x03(\v2\x1d.api.ListRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"T\n" +
	"\x0eEntityResponse\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12#\n" +
	"\x06entity\x18\x02 \x01(\v2\v.api.EntityR\x06entity\"\xa8\x01\n" +
	"\fListResponse\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12'\n" +
	"\bentities\x18\x02 \x03(\v2\v.api.EntityR\bentities\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\\\n" +
	"\x12BatchCreateRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12'\n" +
	"\bentities\x18\x02 \x03(\v2\v.api.EntityR\bentities\"\\\n" +
	"\x12BatchUpdateRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12'\n" +
	"\bentities\x18\x02 \x03(\v2\v.api.EntityR\bentities\"x\n" +
	"\rBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x05R\x03ids\x12#\n" +
	"\raffected_rows\x18\x03 \x01(\x05R\faffectedRows\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"L\n" +
	"\x16GetOrganizationRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x12\x12\n" +
	"\x03inn\x18\x02 \x01(\tH\x00R\x03innB\f\n" +
	"\n" +
	"identifier\"c\n" +
	"\x18ListOrganizationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"H\n" +
	"\x1aSearchOrganizationsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xaf\x02\n" +
	"\x14OrganizationResponse\x125\n" +
	"\forganization\x18\x01 \x01(\v2\x11.api.OrganizationR\forganization\x12*\n" +
	"\taddresses\x18\x02 \x03(\v2\f.api.AddressR\taddresses\x12(\n" +
	"\bcontacts\x18\x03 \x03(\v2\f.api.ContactR\bcontacts\x12J\n" +
	"\x14financial_indicators\x18\x04 \x03(\v2\x17.api.FinancialIndicatorR\x13financialIndicators\x12>\n" +
	"\x10staff_indicators\x18\x05 \x03(\v2\x13.api.StaffIndicatorR\x0fstaffIndicators\"\xb1\x04\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03inn\x18\x02 \x01(\tR\x03inn\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12!\n" +
	"\fspark_status\x18\x05 \x01(\tR\vsparkStatus\x12'\n" +
	"\x0finternal_status\x18\x06 \x01(\tR\x0einternalStatus\x12!\n" +
	"\ffinal_status\x18\a \x01(\tR\vfinalStatus\x12+\n" +
	"\x11registration_date\x18\b \x01(\tR\x10registrationDate\x123\n" +
	"\x16added_to_registry_date\x18\t \x01(\tR\x13addedToRegistryDate\x12,\n" +
	"\x12has_special_status\x18\n" +
	" \x01(\bR\x10hasSpecialStatus\x12:\n" +
	"\x19is_systemically_important\x18\v \x01(\bR\x17isSystemicallyImportant\x12\x1d\n" +
	"\n" +
	"msp_status\x18\f \x01(\tR\tmspStatus\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\faddress_type\x18\x02 \x01(\tR\vaddressType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"\xbf\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vleader_name\x18\x02 \x01(\tR\n" +
	"leaderName\x12!\n" +
	"\fleader_email\x18\x03 \x01(\tR\vleaderEmail\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12#\n" +
	"\rgeneral_email\x18\x06 \x01(\tR\fgeneralEmail\"\xc5\x01\n" +
	"\x12FinancialIndicator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x01R\arevenue\x12\x1d\n" +
	"\n" +
	"net_profit\x18\x04 \x01(\x01R\tnetProfit\x12-\n" +
	"\x12investments_moscow\x18\x05 \x01(\x01R\x11investmentsMoscow\x12#\n" +
	"\rexport_volume\x18\x06 \x01(\x01R\fexportVolume\"\xac\x02\n" +
	"\x0eStaffIndicator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1f\n" +
	"\vtotal_staff\x18\x03 \x01(\x05R\n" +
	"totalStaff\x12!\n" +
	"\fmoscow_staff\x18\x04 \x01(\x05R\vmoscowStaff\x12,\n" +
	"\x12total_payroll_fund\x18\x05 \x01(\x01R\x10totalPayrollFund\x12.\n" +
	"\x13moscow_payroll_fund\x18\x06 \x01(\x01R\x11moscowPayrollFund\x12(\n" +
	"\x10avg_salary_total\x18\a \x01(\x01R\x0eavgSalaryTotal\x12*\n" +
	"\x11avg_salary_moscow\x18\b \x01(\x01R\x0favgSalaryMoscow\"H\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05emailB\f\n" +
	"\n" +
	"identifier\"\xd9\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\arole_id\x18\a \x01(\x05R\x06roleId\"\x92\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"-\n" +
	"\fUserResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.api.UserR\x04user\"\xaf\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\arole_id\x18\a \x01(\x05R\x06roleId\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_verified\x18\t \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x01\n" +
	"\x13CreateInviteRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x05R\x06roleId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x05R\tcreatedBy\x12!\n" +
	"\fexpires_days\x18\x05 \x01(\x05R\vexpiresDays\"+\n" +
	"\x15ValidateInviteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xaa\x01\n" +
	"\x10UseInviteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"5\n" +
	"\x0eInviteResponse\x12#\n" +
	"\x06invite\x18\x01 \x01(\v2\v.api.InviteR\x06invite\"\x93\x02\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x05R\x06roleId\x12\x17\n" +
	"\ais_used\x18\x06 \x01(\bR\x06isUsed\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x89\x01\n" +
	"\x11SubmitFormRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\x05R\x06formId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tform_data\x18\x03 \x01(\fR\bformData\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"B\n" +
	"\x0eGetFormRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\x05R\x06formId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\xc0\x01\n" +
	"\fFormResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\x05R\x06formId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tform_data\x18\x05 \x01(\fR\bformData\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"V\n" +
	"\x17GetFinancialDataRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"P\n" +
	"\x15FinancialDataResponse\x127\n" +
	"\n" +
	"indicators\x18\x01 \x03(\v2\x17.api.FinancialIndicatorR\n" +
	"indicators\"R\n" +
	"\x13GetStaffDataRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"H\n" +
	"\x11StaffDataResponse\x123\n" +
	"\n" +
	"indicators\x18\x01 \x03(\v2\x13.api.StaffIndicatorR\n" +
	"indicators\"\xa6\x01\n" +
	"\x19ListOrganizationsResponse\x127\n" +
	"\rorganizations\x18\x01 \x03(\v2\x11.api.OrganizationR\rorganizations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xc9\t\n" +
	"\vDataService\x121\n" +
	"\x06Create\x12\x12.api.CreateRequest\x1a\x13.api.EntityResponse\x12+\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x13.api.EntityResponse\x121\n" +
	"\x06Update\x12\x12.api.UpdateRequest\x1a\x13.api.EntityResponse\x121\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x13.api.DeleteResponse\x12+\n" +
	"\x04List\x12\x10.api.ListRequest\x1a\x11.api.ListResponse\x12/\n" +
	"\x06Search\x12\x12.api.SearchRequest\x1a\x11.api.ListResponse\x12I\n" +
	"\x0fGetOrganization\x12\x1b.api.GetOrganizationRequest\x1a\x19.api.OrganizationResponse\x12R\n" +
	"\x11ListOrganizations\x12\x1d.api.ListOrganizationsRequest\x1a\x1e.api.ListOrganizationsResponse\x12V\n" +
	"\x13SearchOrganizations\x12\x1f.api.SearchOrganizationsRequest\x1a\x1e.api.ListOrganizationsResponse\x121\n" +
	"\aGetUser\x12\x13.api.GetUserRequest\x1a\x11.api.UserResponse\x127\n" +
	"\n" +
	"CreateUser\x12\x16.api.CreateUserRequest\x1a\x11.api.UserResponse\x127\n" +
	"\n" +
	"UpdateUser\x12\x16.api.UpdateUserRequest\x1a\x11.api.UserResponse\x12=\n" +
	"\fCreateInvite\x12\x18.api.CreateInviteRequest\x1a\x13.api.InviteResponse\x12A\n" +
	"\x0eValidateInvite\x12\x1a.api.ValidateInviteRequest\x1a\x13.api.InviteResponse\x127\n" +
	"\tUseInvite\x12\x15.api.UseInviteRequest\x1a\x13.api.InviteResponse\x127\n" +
	"\n" +
	"SubmitForm\x12\x16.api.SubmitFormRequest\x1a\x11.api.FormResponse\x12L\n" +
	"\x10GetFinancialData\x12\x1c.api.GetFinancialDataRequest\x1a\x1a.api.FinancialDataResponse\x12@\n" +
	"\fGetStaffData\x12\x18.api.GetStaffDataRequest\x1a\x16.api.StaffDataResponse\x12:\n" +
	"\vBatchCreate\x12\x17.api.BatchCreateRequest\x1a\x12.api.BatchResponse\x12:\n" +
	"\vBatchUpdate\x12\x17.api.BatchUpdateRequest\x1a\x12.api.BatchResponseB\aZ\x05./apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_api_proto_goTypes = []any{
	(*Entity)(nil),                     // 0: api.Entity
	(*CreateRequest)(nil),              // 1: api.CreateRequest
	(*GetRequest)(nil),                 // 2: api.GetRequest
	(*UpdateRequest)(nil),              // 3: api.UpdateRequest
	(*DeleteRequest)(nil),              // 4: api.DeleteRequest
	(*DeleteResponse)(nil),             // 5: api.DeleteResponse
	(*ListRequest)(nil),                // 6: api.ListRequest
	(*SearchRequest)(nil),              // 7: api.SearchRequest
	(*EntityResponse)(nil),             // 8: api.EntityResponse
	(*ListResponse)(nil),               // 9: api.ListResponse
	(*BatchCreateRequest)(nil),         // 10: api.BatchCreateRequest
	(*BatchUpdateRequest)(nil),         // 11: api.BatchUpdateRequest
	(*BatchResponse)(nil),              // 12: api.BatchResponse
	(*GetOrganizationRequest)(nil),     // 13: api.GetOrganizationRequest
	(*ListOrganizationsRequest)(nil),   // 14: api.ListOrganizationsRequest
	(*SearchOrganizationsRequest)(nil), // 15: api.SearchOrganizationsRequest
	(*OrganizationResponse)(nil),       // 16: api.OrganizationResponse
	(*Organization)(nil),               // 17: api.Organization
	(*Address)(nil),                    // 18: api.Address
	(*Contact)(nil),                    // 19: api.Contact
	(*FinancialIndicator)(nil),         // 20: api.FinancialIndicator
	(*StaffIndicator)(nil),             // 21: api.StaffIndicator
	(*GetUserRequest)(nil),             // 22: api.GetUserRequest
	(*CreateUserRequest)(nil),          // 23: api.CreateUserRequest
	(*UpdateUserRequest)(nil),          // 24: api.UpdateUserRequest
	(*UserResponse)(nil),               // 25: api.UserResponse
	(*User)(nil),                       // 26: api.User
	(*CreateInviteRequest)(nil),        // 27: api.CreateInviteRequest
	(*ValidateInviteRequest)(nil),      // 28: api.ValidateInviteRequest
	(*UseInviteRequest)(nil),           // 29: api.UseInviteRequest
	(*InviteResponse)(nil),             // 30: api.InviteResponse
	(*Invite)(nil),                     // 31: api.Invite
	(*SubmitFormRequest)(nil),          // 32: api.SubmitFormRequest
	(*GetFormRequest)(nil),             // 33: api.GetFormRequest
	(*FormResponse)(nil),               // 34: api.FormResponse
	(*GetFinancialDataRequest)(nil),    // 35: api.GetFinancialDataRequest
	(*FinancialDataResponse)(nil),      // 36: api.FinancialDataResponse
	(*GetStaffDataRequest)(nil),        // 37: api.GetStaffDataRequest
	(*StaffDataResponse)(nil),          // 38: api.StaffDataResponse
	(*ListOrganizationsResponse)(nil),  // 39: api.ListOrganizationsResponse
	nil,                                // 40: api.Entity.FieldsEntry
	nil,                                // 41: api.Entity.BinaryFieldsEntry
	nil,                                // 42: api.GetRequest.FiltersEntry
	nil,                                // 43: api.ListRequest.FiltersEntry
	(*timestamppb.Timestamp)(nil),      // 44: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	40, // 0: api.Entity.fields:type_name -> api.Entity.FieldsEntry
	41, // 1: api.Entity.binary_fields:type_name -> api.Entity.BinaryFieldsEntry
	0,  // 2: api.CreateRequest.entity:type_name -> api.Entity
	42, // 3: api.GetRequest.filters:type_name -> api.GetRequest.FiltersEntry
	0,  // 4: api.UpdateRequest.entity:type_name -> api.Entity
	43, // 5: api.ListRequest.filters:type_name -> api.ListRequest.FiltersEntry
	0,  // 6: api.EntityResponse.entity:type_name -> api.Entity
	0,  // 7: api.ListResponse.entities:type_name -> api.Entity
	0,  // 8: api.BatchCreateRequest.entities:type_name -> api.Entity
	0,  // 9: api.BatchUpdateRequest.entities:type_name -> api.Entity
	17, // 10: api.OrganizationResponse.organization:type_name -> api.Organization
	18, // 11: api.OrganizationResponse.addresses:type_name -> api.Address
	19, // 12: api.OrganizationResponse.contacts:type_name -> api.Contact
	20, // 13: api.OrganizationResponse.financial_indicators:type_name -> api.FinancialIndicator
	21, // 14: api.OrganizationResponse.staff_indicators:type_name -> api.StaffIndicator
	44, // 15: api.Organization.created_at:type_name -> google.protobuf.Timestamp
	44, // 16: api.Organization.updated_at:type_name -> google.protobuf.Timestamp
	26, // 17: api.UserResponse.user:type_name -> api.User
	44, // 18: api.User.last_login:type_name -> google.protobuf.Timestamp
	44, // 19: api.User.created_at:type_name -> google.protobuf.Timestamp
	44, // 20: api.User.updated_at:type_name -> google.protobuf.Timestamp
	31, // 21: api.InviteResponse.invite:type_name -> api.Invite
	44, // 22: api.Invite.expires_at:type_name -> google.protobuf.Timestamp
	44, // 23: api.Invite.created_at:type_name -> google.protobuf.Timestamp
	44, // 24: api.FormResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 25: api.FinancialDataResponse.indicators:type_name -> api.FinancialIndicator
	21, // 26: api.StaffDataResponse.indicators:type_name -> api.StaffIndicator
	17, // 27: api.ListOrganizationsResponse.organizations:type_name -> api.Organization
	1,  // 28: api.DataService.Create:input_type -> api.CreateRequest
	2,  // 29: api.DataService.Get:input_type -> api.GetRequest
	3,  // 30: api.DataService.Update:input_type -> api.UpdateRequest
	4,  // 31: api.DataService.Delete:input_type -> api.DeleteRequest
	6,  // 32: api.DataService.List:input_type -> api.ListRequest
	7,  // 33: api.DataService.Search:input_type -> api.SearchRequest
	13, // 34: api.DataService.GetOrganization:input_type -> api.GetOrganizationRequest
	14, // 35: api.DataService.ListOrganizations:input_type -> api.ListOrganizationsRequest
	15, // 36: api.DataService.SearchOrganizations:input_type -> api.SearchOrganizationsRequest
	22, // 37: api.DataService.GetUser:input_type -> api.GetUserRequest
	23, // 38: api.DataService.CreateUser:input_type -> api.CreateUserRequest
	24, // 39: api.DataService.UpdateUser:input_type -> api.UpdateUserRequest
	27, // 40: api.DataService.CreateInvite:input_type -> api.CreateInviteRequest
	28, // 41: api.DataService.ValidateInvite:input_type -> api.ValidateInviteRequest
	29, // 42: api.DataService.UseInvite:input_type -> api.UseInviteRequest
	32, // 43: api.DataService.SubmitForm:input_type -> api.SubmitFormRequest
	35, // 44: api.DataService.GetFinancialData:input_type -> api.GetFinancialDataRequest
	37, // 45: api.DataService.GetStaffData:input_type -> api.GetStaffDataRequest
	10, // 46: api.DataService.BatchCreate:input_type -> api.BatchCreateRequest
	11, // 47: api.DataService.BatchUpdate:input_type -> api.BatchUpdateRequest
	8,  // 48: api.DataService.Create:output_type -> api.EntityResponse
	8,  // 49: api.DataService.Get:output_type -> api.EntityResponse
	8,  // 50: api.DataService.Update:output_type -> api.EntityResponse
	5,  // 51: api.DataService.Delete:output_type -> api.DeleteResponse
	9,  // 52: api.DataService.List:output_type -> api.ListResponse
	9,  // 53: api.DataService.Search:output_type -> api.ListResponse
	16, // 54: api.DataService.GetOrganization:output_type -> api.OrganizationResponse
	39, // 55: api.DataService.ListOrganizations:output_type -> api.ListOrganizationsResponse
	39, // 56: api.DataService.SearchOrganizations:output_type -> api.ListOrganizationsResponse
	25, // 57: api.DataService.GetUser:output_type -> api.UserResponse
	25, // 58: api.DataService.CreateUser:output_type -> api.UserResponse
	25, // 59: api.DataService.UpdateUser:output_type -> api.UserResponse
	30, // 60: api.DataService.CreateInvite:output_type -> api.InviteResponse
	30, // 61: api.DataService.ValidateInvite:output_type -> api.InviteResponse
	30, // 62: api.DataService.UseInvite:output_type -> api.InviteResponse
	34, // 63: api.DataService.SubmitForm:output_type -> api.FormResponse
	36, // 64: api.DataService.GetFinancialData:output_type -> api.FinancialDataResponse
	38, // 65: api.DataService.GetStaffData:output_type -> api.StaffDataResponse
	12, // 66: api.DataService.BatchCreate:output_type -> api.BatchResponse
	12, // 67: api.DataService.BatchUpdate:output_type -> api.BatchResponse
	48, // [48:68] is the sub-list for method output_type
	28, // [28:48] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[13].OneofWrappers = []any{
		(*GetOrganizationRequest_Id)(nil),
		(*GetOrganizationRequest_Inn)(nil),
	}
	file_api_proto_msgTypes[22].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
