// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: database.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Database Registration
type DatabaseRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseRegistrationRequest) Reset() {
	*x = DatabaseRegistrationRequest{}
	mi := &file_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseRegistrationRequest) ProtoMessage() {}

func (x *DatabaseRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseRegistrationRequest.ProtoReflect.Descriptor instead.
func (*DatabaseRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseRegistrationRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DatabaseRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CommonName    string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseRegistrationResponse) Reset() {
	*x = DatabaseRegistrationResponse{}
	mi := &file_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseRegistrationResponse) ProtoMessage() {}

func (x *DatabaseRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseRegistrationResponse.ProtoReflect.Descriptor instead.
func (*DatabaseRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DatabaseRegistrationResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DatabaseRegistrationResponse) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *DatabaseRegistrationResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DatabaseRegistrationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Command System
type CommandRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandRequest_Create
	//	*CommandRequest_Get
	//	*CommandRequest_Update
	//	*CommandRequest_Delete
	//	*CommandRequest_List
	//	*CommandRequest_Search
	//	*CommandRequest_BatchCreate
	//	*CommandRequest_BatchUpdate
	//	*CommandRequest_GetOrganization
	//	*CommandRequest_ListOrganizations
	//	*CommandRequest_SearchOrganizations
	//	*CommandRequest_GetUser
	//	*CommandRequest_CreateUser
	//	*CommandRequest_UpdateUser
	//	*CommandRequest_CreateInvite
	//	*CommandRequest_ValidateInvite
	//	*CommandRequest_UseInvite
	//	*CommandRequest_SubmitForm
	//	*CommandRequest_GetFinancialData
	//	*CommandRequest_GetStaffData
	//	*CommandRequest_SystemCommand
	Command       isCommandRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetCommand() isCommandRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetCreate() *CreateRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *CommandRequest) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *CommandRequest) GetUpdate() *UpdateRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *CommandRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *CommandRequest) GetList() *ListRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CommandRequest) GetSearch() *SearchRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Search); ok {
			return x.Search
		}
	}
	return nil
}

func (x *CommandRequest) GetBatchCreate() *BatchCreateRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_BatchCreate); ok {
			return x.BatchCreate
		}
	}
	return nil
}

func (x *CommandRequest) GetBatchUpdate() *BatchUpdateRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_BatchUpdate); ok {
			return x.BatchUpdate
		}
	}
	return nil
}

func (x *CommandRequest) GetGetOrganization() *GetOrganizationRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_GetOrganization); ok {
			return x.GetOrganization
		}
	}
	return nil
}

func (x *CommandRequest) GetListOrganizations() *ListOrganizationsRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ListOrganizations); ok {
			return x.ListOrganizations
		}
	}
	return nil
}

func (x *CommandRequest) GetSearchOrganizations() *SearchOrganizationsRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_SearchOrganizations); ok {
			return x.SearchOrganizations
		}
	}
	return nil
}

func (x *CommandRequest) GetGetUser() *GetUserRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_GetUser); ok {
			return x.GetUser
		}
	}
	return nil
}

func (x *CommandRequest) GetCreateUser() *CreateUserRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *CommandRequest) GetUpdateUser() *UpdateUserRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_UpdateUser); ok {
			return x.UpdateUser
		}
	}
	return nil
}

func (x *CommandRequest) GetCreateInvite() *CreateInviteRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_CreateInvite); ok {
			return x.CreateInvite
		}
	}
	return nil
}

func (x *CommandRequest) GetValidateInvite() *ValidateInviteRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ValidateInvite); ok {
			return x.ValidateInvite
		}
	}
	return nil
}

func (x *CommandRequest) GetUseInvite() *UseInviteRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_UseInvite); ok {
			return x.UseInvite
		}
	}
	return nil
}

func (x *CommandRequest) GetSubmitForm() *SubmitFormRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_SubmitForm); ok {
			return x.SubmitForm
		}
	}
	return nil
}

func (x *CommandRequest) GetGetFinancialData() *GetFinancialDataRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_GetFinancialData); ok {
			return x.GetFinancialData
		}
	}
	return nil
}

func (x *CommandRequest) GetGetStaffData() *GetStaffDataRequest {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_GetStaffData); ok {
			return x.GetStaffData
		}
	}
	return nil
}

func (x *CommandRequest) GetSystemCommand() string {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_SystemCommand); ok {
			return x.SystemCommand
		}
	}
	return ""
}

type isCommandRequest_Command interface {
	isCommandRequest_Command()
}

type CommandRequest_Create struct {
	// Универсальные CRUD команды
	Create *CreateRequest `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type CommandRequest_Get struct {
	Get *GetRequest `protobuf:"bytes,3,opt,name=get,proto3,oneof"`
}

type CommandRequest_Update struct {
	Update *UpdateRequest `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

type CommandRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type CommandRequest_List struct {
	List *ListRequest `protobuf:"bytes,6,opt,name=list,proto3,oneof"`
}

type CommandRequest_Search struct {
	Search *SearchRequest `protobuf:"bytes,7,opt,name=search,proto3,oneof"`
}

type CommandRequest_BatchCreate struct {
	BatchCreate *BatchCreateRequest `protobuf:"bytes,8,opt,name=batch_create,json=batchCreate,proto3,oneof"`
}

type CommandRequest_BatchUpdate struct {
	BatchUpdate *BatchUpdateRequest `protobuf:"bytes,9,opt,name=batch_update,json=batchUpdate,proto3,oneof"`
}

type CommandRequest_GetOrganization struct {
	// Специализированные команды
	GetOrganization *GetOrganizationRequest `protobuf:"bytes,10,opt,name=get_organization,json=getOrganization,proto3,oneof"`
}

type CommandRequest_ListOrganizations struct {
	ListOrganizations *ListOrganizationsRequest `protobuf:"bytes,11,opt,name=list_organizations,json=listOrganizations,proto3,oneof"`
}

type CommandRequest_SearchOrganizations struct {
	SearchOrganizations *SearchOrganizationsRequest `protobuf:"bytes,12,opt,name=search_organizations,json=searchOrganizations,proto3,oneof"`
}

type CommandRequest_GetUser struct {
	GetUser *GetUserRequest `protobuf:"bytes,13,opt,name=get_user,json=getUser,proto3,oneof"`
}

type CommandRequest_CreateUser struct {
	CreateUser *CreateUserRequest `protobuf:"bytes,14,opt,name=create_user,json=createUser,proto3,oneof"`
}

type CommandRequest_UpdateUser struct {
	UpdateUser *UpdateUserRequest `protobuf:"bytes,15,opt,name=update_user,json=updateUser,proto3,oneof"`
}

type CommandRequest_CreateInvite struct {
	CreateInvite *CreateInviteRequest `protobuf:"bytes,16,opt,name=create_invite,json=createInvite,proto3,oneof"`
}

type CommandRequest_ValidateInvite struct {
	ValidateInvite *ValidateInviteRequest `protobuf:"bytes,17,opt,name=validate_invite,json=validateInvite,proto3,oneof"`
}

type CommandRequest_UseInvite struct {
	UseInvite *UseInviteRequest `protobuf:"bytes,18,opt,name=use_invite,json=useInvite,proto3,oneof"`
}

type CommandRequest_SubmitForm struct {
	SubmitForm *SubmitFormRequest `protobuf:"bytes,19,opt,name=submit_form,json=submitForm,proto3,oneof"`
}

type CommandRequest_GetFinancialData struct {
	GetFinancialData *GetFinancialDataRequest `protobuf:"bytes,20,opt,name=get_financial_data,json=getFinancialData,proto3,oneof"`
}

type CommandRequest_GetStaffData struct {
	GetStaffData *GetStaffDataRequest `protobuf:"bytes,21,opt,name=get_staff_data,json=getStaffData,proto3,oneof"`
}

type CommandRequest_SystemCommand struct {
	// Системные команды
	SystemCommand string `protobuf:"bytes,22,opt,name=system_command,json=systemCommand,proto3,oneof"`
}

func (*CommandRequest_Create) isCommandRequest_Command() {}

func (*CommandRequest_Get) isCommandRequest_Command() {}

func (*CommandRequest_Update) isCommandRequest_Command() {}

func (*CommandRequest_Delete) isCommandRequest_Command() {}

func (*CommandRequest_List) isCommandRequest_Command() {}

func (*CommandRequest_Search) isCommandRequest_Command() {}

func (*CommandRequest_BatchCreate) isCommandRequest_Command() {}

func (*CommandRequest_BatchUpdate) isCommandRequest_Command() {}

func (*CommandRequest_GetOrganization) isCommandRequest_Command() {}

func (*CommandRequest_ListOrganizations) isCommandRequest_Command() {}

func (*CommandRequest_SearchOrganizations) isCommandRequest_Command() {}

func (*CommandRequest_GetUser) isCommandRequest_Command() {}

func (*CommandRequest_CreateUser) isCommandRequest_Command() {}

func (*CommandRequest_UpdateUser) isCommandRequest_Command() {}

func (*CommandRequest_CreateInvite) isCommandRequest_Command() {}

func (*CommandRequest_ValidateInvite) isCommandRequest_Command() {}

func (*CommandRequest_UseInvite) isCommandRequest_Command() {}

func (*CommandRequest_SubmitForm) isCommandRequest_Command() {}

func (*CommandRequest_GetFinancialData) isCommandRequest_Command() {}

func (*CommandRequest_GetStaffData) isCommandRequest_Command() {}

func (*CommandRequest_SystemCommand) isCommandRequest_Command() {}

type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*CommandResponse_Entity
	//	*CommandResponse_List
	//	*CommandResponse_Delete
	//	*CommandResponse_Batch
	//	*CommandResponse_Organization
	//	*CommandResponse_Organizations
	//	*CommandResponse_User
	//	*CommandResponse_Invite
	//	*CommandResponse_Form
	//	*CommandResponse_FinancialData
	//	*CommandResponse_StaffData
	//	*CommandResponse_Error
	//	*CommandResponse_Ready
	//	*CommandResponse_System
	Response      isCommandResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetResponse() isCommandResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CommandResponse) GetEntity() *EntityResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *CommandResponse) GetList() *ListResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *CommandResponse) GetDelete() *DeleteResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *CommandResponse) GetBatch() *BatchResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *CommandResponse) GetOrganization() *OrganizationResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Organization); ok {
			return x.Organization
		}
	}
	return nil
}

func (x *CommandResponse) GetOrganizations() *ListOrganizationsResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Organizations); ok {
			return x.Organizations
		}
	}
	return nil
}

func (x *CommandResponse) GetUser() *UserResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *CommandResponse) GetInvite() *InviteResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Invite); ok {
			return x.Invite
		}
	}
	return nil
}

func (x *CommandResponse) GetForm() *FormResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Form); ok {
			return x.Form
		}
	}
	return nil
}

func (x *CommandResponse) GetFinancialData() *FinancialDataResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_FinancialData); ok {
			return x.FinancialData
		}
	}
	return nil
}

func (x *CommandResponse) GetStaffData() *StaffDataResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_StaffData); ok {
			return x.StaffData
		}
	}
	return nil
}

func (x *CommandResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *CommandResponse) GetReady() *ReadyMessage {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *CommandResponse) GetSystem() *SystemResponse {
	if x != nil {
		if x, ok := x.Response.(*CommandResponse_System); ok {
			return x.System
		}
	}
	return nil
}

type isCommandResponse_Response interface {
	isCommandResponse_Response()
}

type CommandResponse_Entity struct {
	// Универсальные CRUD ответы
	Entity *EntityResponse `protobuf:"bytes,2,opt,name=entity,proto3,oneof"`
}

type CommandResponse_List struct {
	List *ListResponse `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type CommandResponse_Delete struct {
	Delete *DeleteResponse `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type CommandResponse_Batch struct {
	Batch *BatchResponse `protobuf:"bytes,5,opt,name=batch,proto3,oneof"`
}

type CommandResponse_Organization struct {
	// Специализированные ответы
	Organization *OrganizationResponse `protobuf:"bytes,6,opt,name=organization,proto3,oneof"`
}

type CommandResponse_Organizations struct {
	Organizations *ListOrganizationsResponse `protobuf:"bytes,7,opt,name=organizations,proto3,oneof"`
}

type CommandResponse_User struct {
	User *UserResponse `protobuf:"bytes,8,opt,name=user,proto3,oneof"`
}

type CommandResponse_Invite struct {
	Invite *InviteResponse `protobuf:"bytes,9,opt,name=invite,proto3,oneof"`
}

type CommandResponse_Form struct {
	Form *FormResponse `protobuf:"bytes,10,opt,name=form,proto3,oneof"`
}

type CommandResponse_FinancialData struct {
	FinancialData *FinancialDataResponse `protobuf:"bytes,11,opt,name=financial_data,json=financialData,proto3,oneof"`
}

type CommandResponse_StaffData struct {
	StaffData *StaffDataResponse `protobuf:"bytes,12,opt,name=staff_data,json=staffData,proto3,oneof"`
}

type CommandResponse_Error struct {
	// Системные ответы
	Error *ErrorResponse `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

type CommandResponse_Ready struct {
	Ready *ReadyMessage `protobuf:"bytes,14,opt,name=ready,proto3,oneof"`
}

type CommandResponse_System struct {
	System *SystemResponse `protobuf:"bytes,15,opt,name=system,proto3,oneof"`
}

func (*CommandResponse_Entity) isCommandResponse_Response() {}

func (*CommandResponse_List) isCommandResponse_Response() {}

func (*CommandResponse_Delete) isCommandResponse_Response() {}

func (*CommandResponse_Batch) isCommandResponse_Response() {}

func (*CommandResponse_Organization) isCommandResponse_Response() {}

func (*CommandResponse_Organizations) isCommandResponse_Response() {}

func (*CommandResponse_User) isCommandResponse_Response() {}

func (*CommandResponse_Invite) isCommandResponse_Response() {}

func (*CommandResponse_Form) isCommandResponse_Response() {}

func (*CommandResponse_FinancialData) isCommandResponse_Response() {}

func (*CommandResponse_StaffData) isCommandResponse_Response() {}

func (*CommandResponse_Error) isCommandResponse_Response() {}

func (*CommandResponse_Ready) isCommandResponse_Response() {}

func (*CommandResponse_System) isCommandResponse_Response() {}

type SystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemResponse) Reset() {
	*x = SystemResponse{}
	mi := &file_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResponse) ProtoMessage() {}

func (x *SystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResponse.ProtoReflect.Descriptor instead.
func (*SystemResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{4}
}

func (x *SystemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SystemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SystemResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyMessage) Reset() {
	*x = ReadyMessage{}
	mi := &file_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyMessage) ProtoMessage() {}

func (x *ReadyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyMessage.ProtoReflect.Descriptor instead.
func (*ReadyMessage) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{5}
}

func (x *ReadyMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_database_proto protoreflect.FileDescriptor

const file_database_proto_rawDesc = "" +
	"\n" +
	"\x0edatabase.proto\x12\x03api\x1a\tapi.proto\"<\n" +
	"\x1bDatabaseRegistrationRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\xbb\x01\n" +
	"\x1cDatabaseRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x87\n" +
	"\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x06create\x18\x02 \x01(\v2\x12.api.CreateRequestH\x00R\x06create\x12#\n" +
	"\x03get\x18\x03 \x01(\v2\x0f.api.GetRequestH\x00R\x03get\x12,\n" +
	"\x06update\x18\x04 \x01(\v2\x12.api.UpdateRequestH\x00R\x06update\x12,\n" +
	"\x06delete\x18\x05 \x01(\v2\x12.api.DeleteRequestH\x00R\x06delete\x12&\n" +
	"\x04list\x18\x06 \x01(\v2\x10.api.ListRequestH\x00R\x04list\x12,\n" +
	"\x06search\x18\a \x01(\v2\x12.api.SearchRequestH\x00R\x06search\x12<\n" +
	"\fbatch_create\x18\b \x01(\v2\x17.api.BatchCreateRequestH\x00R\vbatchCreate\x12<\n" +
	"\fbatch_update\x18\t \x01(\v2\x17.api.BatchUpdateRequestH\x00R\vbatchUpdate\x12H\n" +
	"\x10get_organization\x18\n" +
	" \x01(\v2\x1b.api.GetOrganizationRequestH\x00R\x0fgetOrganization\x12N\n" +
	"\x12list_organizations\x18\v \x01(\v2\x1d.api.ListOrganizationsRequestH\x00R\x11listOrganizations\x12T\n" +
	"\x14search_organizations\x18\f \x01(\v2\x1f.api.SearchOrganizationsRequestH\x00R\x13searchOrganizations\x120\n" +
	"\bget_user\x18\r \x01(\v2\x13.api.GetUserRequestH\x00R\agetUser\x129\n" +
	"\vcreate_user\x18\x0e \x01(\v2\x16.api.CreateUserRequestH\x00R\n" +
	"createUser\x129\n" +
	"\vupdate_user\x18\x0f \x01(\v2\x16.api.UpdateUserRequestH\x00R\n" +
	"updateUser\x12?\n" +
	"\rcreate_invite\x18\x10 \x01(\v2\x18.api.CreateInviteRequestH\x00R\fcreateInvite\x12E\n" +
	"\x0fvalidate_invite\x18\x11 \x01(\v2\x1a.api.ValidateInviteRequestH\x00R\x0evalidateInvite\x126\n" +
	"\n" +
	"use_invite\x18\x12 \x01(\v2\x15.api.UseInviteRequestH\x00R\tuseInvite\x129\n" +
	"\vsubmit_form\x18\x13 \x01(\v2\x16.api.SubmitFormRequestH\x00R\n" +
	"submitForm\x12L\n" +
	"\x12get_financial_data\x18\x14 \x01(\v2\x1c.api.GetFinancialDataRequestH\x00R\x10getFinancialData\x12@\n" +
	"\x0eget_staff_data\x18\x15 \x01(\v2\x18.api.GetStaffDataRequestH\x00R\fgetStaffData\x12'\n" +
	"\x0esystem_command\x18\x16 \x01(\tH\x00R\rsystemCommandB\t\n" +
	"\acommand\"\xfd\x05\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x06entity\x18\x02 \x01(\v2\x13.api.EntityResponseH\x00R\x06entity\x12'\n" +
	"\x04list\x18\x03 \x01(\v2\x11.api.ListResponseH\x00R\x04list\x12-\n" +
	"\x06delete\x18\x04 \x01(\v2\x13.api.DeleteResponseH\x00R\x06delete\x12*\n" +
	"\x05batch\x18\x05 \x01(\v2\x12.api.BatchResponseH\x00R\x05batch\x12?\n" +
	"\forganization\x18\x06 \x01(\v2\x19.api.OrganizationResponseH\x00R\forganization\x12F\n" +
	"\rorganizations\x18\a \x01(\v2\x1e.api.ListOrganizationsResponseH\x00R\rorganizations\x12'\n" +
	"\x04user\x18\b \x01(\v2\x11.api.UserResponseH\x00R\x04user\x12-\n" +
	"\x06invite\x18\t \x01(\v2\x13.api.InviteResponseH\x00R\x06invite\x12'\n" +
	"\x04form\x18\n" +
	" \x01(\v2\x11.api.FormResponseH\x00R\x04form\x12C\n" +
	"\x0efinancial_data\x18\v \x01(\v2\x1a.api.FinancialDataResponseH\x00R\rfinancialData\x127\n" +
	"\n" +
	"staff_data\x18\f \x01(\v2\x16.api.StaffDataResponseH\x00R\tstaffData\x12*\n" +
	"\x05error\x18\r \x01(\v2\x12.api.ErrorResponseH\x00R\x05error\x12)\n" +
	"\x05ready\x18\x0e \x01(\v2\x11.api.ReadyMessageH\x00R\x05ready\x12-\n" +
	"\x06system\x18\x0f \x01(\v2\x13.api.SystemResponseH\x00R\x06systemB\n" +
	"\n" +
	"\bresponse\"\xb0\x01\n" +
	"\x0eSystemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.api.SystemResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\fReadyMessage\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"W\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails2\xaa\x01\n" +
	"\x0fDatabaseService\x12>\n" +
	"\rCommandStream\x12\x14.api.CommandResponse\x1a\x13.api.CommandRequest(\x010\x01\x12W\n" +
	"\x10RegisterDatabase\x12 .api.DatabaseRegistrationRequest\x1a!.api.DatabaseRegistrationResponseB\aZ\x05./apib\x06proto3"

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData []byte
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)))
	})
	return file_database_proto_rawDescData
}

var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_database_proto_goTypes = []any{
	(*DatabaseRegistrationRequest)(nil),  // 0: api.DatabaseRegistrationRequest
	(*DatabaseRegistrationResponse)(nil), // 1: api.DatabaseRegistrationResponse
	(*CommandRequest)(nil),               // 2: api.CommandRequest
	(*CommandResponse)(nil),              // 3: api.CommandResponse
	(*SystemResponse)(nil),               // 4: api.SystemResponse
	(*ReadyMessage)(nil),                 // 5: api.ReadyMessage
	(*ErrorResponse)(nil),                // 6: api.ErrorResponse
	nil,                                  // 7: api.SystemResponse.DataEntry
	(*CreateRequest)(nil),                // 8: api.CreateRequest
	(*GetRequest)(nil),                   // 9: api.GetRequest
	(*UpdateRequest)(nil),                // 10: api.UpdateRequest
	(*DeleteRequest)(nil),                // 11: api.DeleteRequest
	(*ListRequest)(nil),                  // 12: api.ListRequest
	(*SearchRequest)(nil),                // 13: api.SearchRequest
	(*BatchCreateRequest)(nil),           // 14: api.BatchCreateRequest
	(*BatchUpdateRequest)(nil),           // 15: api.BatchUpdateRequest
	(*GetOrganizationRequest)(nil),       // 16: api.GetOrganizationRequest
	(*ListOrganizationsRequest)(nil),     // 17: api.ListOrganizationsRequest
	(*SearchOrganizationsRequest)(nil),   // 18: api.SearchOrganizationsRequest
	(*GetUserRequest)(nil),               // 19: api.GetUserRequest
	(*CreateUserRequest)(nil),            // 20: api.CreateUserRequest
	(*UpdateUserRequest)(nil),            // 21: api.UpdateUserRequest
	(*CreateInviteRequest)(nil),          // 22: api.CreateInviteRequest
	(*ValidateInviteRequest)(nil),        // 23: api.ValidateInviteRequest
	(*UseInviteRequest)(nil),             // 24: api.UseInviteRequest
	(*SubmitFormRequest)(nil),            // 25: api.SubmitFormRequest
	(*GetFinancialDataRequest)(nil),      // 26: api.GetFinancialDataRequest
	(*GetStaffDataRequest)(nil),          // 27: api.GetStaffDataRequest
	(*EntityResponse)(nil),               // 28: api.EntityResponse
	(*ListResponse)(nil),                 // 29: api.ListResponse
	(*DeleteResponse)(nil),               // 30: api.DeleteResponse
	(*BatchResponse)(nil),                // 31: api.BatchResponse
	(*OrganizationResponse)(nil),         // 32: api.OrganizationResponse
	(*ListOrganizationsResponse)(nil),    // 33: api.ListOrganizationsResponse
	(*UserResponse)(nil),                 // 34: api.UserResponse
	(*InviteResponse)(nil),               // 35: api.InviteResponse
	(*FormResponse)(nil),                 // 36: api.FormResponse
	(*FinancialDataResponse)(nil),        // 37: api.FinancialDataResponse
	(*StaffDataResponse)(nil),            // 38: api.StaffDataResponse
}
var file_database_proto_depIdxs = []int32{
	8,  // 0: api.CommandRequest.create:type_name -> api.CreateRequest
	9,  // 1: api.CommandRequest.get:type_name -> api.GetRequest
	10, // 2: api.CommandRequest.update:type_name -> api.UpdateRequest
	11, // 3: api.CommandRequest.delete:type_name -> api.DeleteRequest
	12, // 4: api.CommandRequest.list:type_name -> api.ListRequest
	13, // 5: api.CommandRequest.search:type_name -> api.SearchRequest
	14, // 6: api.CommandRequest.batch_create:type_name -> api.BatchCreateRequest
	15, // 7: api.CommandRequest.batch_update:type_name -> api.BatchUpdateRequest
	16, // 8: api.CommandRequest.get_organization:type_name -> api.GetOrganizationRequest
	17, // 9: api.CommandRequest.list_organizations:type_name -> api.ListOrganizationsRequest
	18, // 10: api.CommandRequest.search_organizations:type_name -> api.SearchOrganizationsRequest
	19, // 11: api.CommandRequest.get_user:type_name -> api.GetUserRequest
	20, // 12: api.CommandRequest.create_user:type_name -> api.CreateUserRequest
	21, // 13: api.CommandRequest.update_user:type_name -> api.UpdateUserRequest
	22, // 14: api.CommandRequest.create_invite:type_name -> api.CreateInviteRequest
	23, // 15: api.CommandRequest.validate_invite:type_name -> api.ValidateInviteRequest
	24, // 16: api.CommandRequest.use_invite:type_name -> api.UseInviteRequest
	25, // 17: api.CommandRequest.submit_form:type_name -> api.SubmitFormRequest
	26, // 18: api.CommandRequest.get_financial_data:type_name -> api.GetFinancialDataRequest
	27, // 19: api.CommandRequest.get_staff_data:type_name -> api.GetStaffDataRequest
	28, // 20: api.CommandResponse.entity:type_name -> api.EntityResponse
	29, // 21: api.CommandResponse.list:type_name -> api.ListResponse
	30, // 22: api.CommandResponse.delete:type_name -> api.DeleteResponse
	31, // 23: api.CommandResponse.batch:type_name -> api.BatchResponse
	32, // 24: api.CommandResponse.organization:type_name -> api.OrganizationResponse
	33, // 25: api.CommandResponse.organizations:type_name -> api.ListOrganizationsResponse
	34, // 26: api.CommandResponse.user:type_name -> api.UserResponse
	35, // 27: api.CommandResponse.invite:type_name -> api.InviteResponse
	36, // 28: api.CommandResponse.form:type_name -> api.FormResponse
	37, // 29: api.CommandResponse.financial_data:type_name -> api.FinancialDataResponse
	38, // 30: api.CommandResponse.staff_data:type_name -> api.StaffDataResponse
	6,  // 31: api.CommandResponse.error:type_name -> api.ErrorResponse
	5,  // 32: api.CommandResponse.ready:type_name -> api.ReadyMessage
	4,  // 33: api.CommandResponse.system:type_name -> api.SystemResponse
	7,  // 34: api.SystemResponse.data:type_name -> api.SystemResponse.DataEntry
	3,  // 35: api.DatabaseService.CommandStream:input_type -> api.CommandResponse
	0,  // 36: api.DatabaseService.RegisterDatabase:input_type -> api.DatabaseRegistrationRequest
	2,  // 37: api.DatabaseService.CommandStream:output_type -> api.CommandRequest
	1,  // 38: api.DatabaseService.RegisterDatabase:output_type -> api.DatabaseRegistrationResponse
	37, // [37:39] is the sub-list for method output_type
	35, // [35:37] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	file_api_proto_init()
	file_database_proto_msgTypes[2].OneofWrappers = []any{
		(*CommandRequest_Create)(nil),
		(*CommandRequest_Get)(nil),
		(*CommandRequest_Update)(nil),
		(*CommandRequest_Delete)(nil),
		(*CommandRequest_List)(nil),
		(*CommandRequest_Search)(nil),
		(*CommandRequest_BatchCreate)(nil),
		(*CommandRequest_BatchUpdate)(nil),
		(*CommandRequest_GetOrganization)(nil),
		(*CommandRequest_ListOrganizations)(nil),
		(*CommandRequest_SearchOrganizations)(nil),
		(*CommandRequest_GetUser)(nil),
		(*CommandRequest_CreateUser)(nil),
		(*CommandRequest_UpdateUser)(nil),
		(*CommandRequest_CreateInvite)(nil),
		(*CommandRequest_ValidateInvite)(nil),
		(*CommandRequest_UseInvite)(nil),
		(*CommandRequest_SubmitForm)(nil),
		(*CommandRequest_GetFinancialData)(nil),
		(*CommandRequest_GetStaffData)(nil),
		(*CommandRequest_SystemCommand)(nil),
	}
	file_database_proto_msgTypes[3].OneofWrappers = []any{
		(*CommandResponse_Entity)(nil),
		(*CommandResponse_List)(nil),
		(*CommandResponse_Delete)(nil),
		(*CommandResponse_Batch)(nil),
		(*CommandResponse_Organization)(nil),
		(*CommandResponse_Organizations)(nil),
		(*CommandResponse_User)(nil),
		(*CommandResponse_Invite)(nil),
		(*CommandResponse_Form)(nil),
		(*CommandResponse_FinancialData)(nil),
		(*CommandResponse_StaffData)(nil),
		(*CommandResponse_Error)(nil),
		(*CommandResponse_Ready)(nil),
		(*CommandResponse_System)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_proto_rawDesc), len(file_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
